
package nz.co.aetheric.magus.ioun;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IContentVaultService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IContentVaultService {


    /**
     * 
     * @param id
     * @param targetID
     * @return
     *     returns nz.co.aetheric.magus.ioun.IdentifierWithVersion
     * @throws IContentVaultServiceCommitTooMuchContentFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Commit", action = "http://tempuri.org/IContentVaultService/Commit")
    @WebResult(name = "CommitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Commit", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.Commit")
    @ResponseWrapper(localName = "CommitResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.CommitResponse")
    public IdentifierWithVersion commit(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        ContentIdentifier id,
        @WebParam(name = "targetID", targetNamespace = "http://tempuri.org/")
        ContentIdentifier targetID)
        throws IContentVaultServiceCommitTooMuchContentFaultFaultFaultMessage
    ;

    /**
     * 
     * @param typeID
     * @return
     *     returns nz.co.aetheric.magus.ioun.ContentIdentifier
     * @throws IContentVaultServiceCreateTooMuchScratchFaultFaultFaultMessage
     * @throws IContentVaultServiceCreateTooMuchContentFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Create", action = "http://tempuri.org/IContentVaultService/Create")
    @WebResult(name = "CreateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Create", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.CreateResponse")
    public ContentIdentifier create(
        @WebParam(name = "typeID", targetNamespace = "http://tempuri.org/")
        Integer typeID)
        throws IContentVaultServiceCreateTooMuchContentFaultFaultFaultMessage, IContentVaultServiceCreateTooMuchScratchFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     */
    @WebMethod(operationName = "DeleteContent", action = "http://tempuri.org/IContentVaultService/DeleteContent")
    @RequestWrapper(localName = "DeleteContent", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.DeleteContent")
    @ResponseWrapper(localName = "DeleteContentResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.DeleteContentResponse")
    public void deleteContent(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        ContentIdentifier id);

    /**
     * 
     * @param id
     * @return
     *     returns nz.co.aetheric.magus.ioun.ContentIdentifier
     * @throws IContentVaultServiceEditTooMuchContentFaultFaultFaultMessage
     * @throws IContentVaultServiceEditTooMuchScratchFaultFaultFaultMessage
     */
    @WebMethod(operationName = "Edit", action = "http://tempuri.org/IContentVaultService/Edit")
    @WebResult(name = "EditResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Edit", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.Edit")
    @ResponseWrapper(localName = "EditResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.EditResponse")
    public ContentIdentifier edit(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        ContentIdentifier id)
        throws IContentVaultServiceEditTooMuchContentFaultFaultFaultMessage, IContentVaultServiceEditTooMuchScratchFaultFaultFaultMessage
    ;

    /**
     * 
     * @param contentType
     * @return
     *     returns nz.co.aetheric.magus.ioun.ArrayOfContentInfo
     */
    @WebMethod(operationName = "GetAvailableContent", action = "http://tempuri.org/IContentVaultService/GetAvailableContent")
    @WebResult(name = "GetAvailableContentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAvailableContent", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetAvailableContent")
    @ResponseWrapper(localName = "GetAvailableContentResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetAvailableContentResponse")
    public ArrayOfContentInfo getAvailableContent(
        @WebParam(name = "contentType", targetNamespace = "http://tempuri.org/")
        Integer contentType);

    /**
     * 
     * @param id
     * @param version
     * @return
     *     returns nz.co.aetheric.magus.ioun.DataWithVersion
     */
    @WebMethod(operationName = "GetData", action = "http://tempuri.org/IContentVaultService/GetData")
    @WebResult(name = "GetDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetDataResponse")
    public DataWithVersion getData(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        ContentIdentifier id,
        @WebParam(name = "version", targetNamespace = "http://tempuri.org/")
        byte[] version);

    /**
     * 
     * @param contentType
     * @return
     *     returns nz.co.aetheric.magus.ioun.ArrayOfContentInfo
     */
    @WebMethod(operationName = "GetDeletedContent", action = "http://tempuri.org/IContentVaultService/GetDeletedContent")
    @WebResult(name = "GetDeletedContentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDeletedContent", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetDeletedContent")
    @ResponseWrapper(localName = "GetDeletedContentResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetDeletedContentResponse")
    public ArrayOfContentInfo getDeletedContent(
        @WebParam(name = "contentType", targetNamespace = "http://tempuri.org/")
        Integer contentType);

    /**
     * 
     * @param contentType
     * @return
     *     returns nz.co.aetheric.magus.ioun.ArrayOfContentInfo
     */
    @WebMethod(operationName = "GetOfficialContent", action = "http://tempuri.org/IContentVaultService/GetOfficialContent")
    @WebResult(name = "GetOfficialContentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOfficialContent", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetOfficialContent")
    @ResponseWrapper(localName = "GetOfficialContentResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetOfficialContentResponse")
    public ArrayOfContentInfo getOfficialContent(
        @WebParam(name = "contentType", targetNamespace = "http://tempuri.org/")
        Integer contentType);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserID", action = "http://tempuri.org/IContentVaultService/GetUserID")
    @WebResult(name = "GetUserIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserID", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetUserID")
    @ResponseWrapper(localName = "GetUserIDResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.GetUserIDResponse")
    public String getUserID();

    /**
     * 
     * @param userName
     * @param password
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/IContentVaultService/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.LoginResponse")
    public Boolean login(
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        byte[] password);

    /**
     * 
     * @param id
     */
    @WebMethod(operationName = "UndeleteContent", action = "http://tempuri.org/IContentVaultService/UndeleteContent")
    @RequestWrapper(localName = "UndeleteContent", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.UndeleteContent")
    @ResponseWrapper(localName = "UndeleteContentResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.UndeleteContentResponse")
    public void undeleteContent(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        ContentIdentifier id);

    /**
     * 
     * @param id
     * @param details
     * @param data
     * @return
     *     returns byte[]
     * @throws IContentVaultServiceUpdateDataContentNotFoundFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UpdateData", action = "http://tempuri.org/IContentVaultService/UpdateData")
    @WebResult(name = "UpdateDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateData", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.UpdateData")
    @ResponseWrapper(localName = "UpdateDataResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.UpdateDataResponse")
    public byte[] updateData(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        ContentIdentifier id,
        @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
        byte[] data,
        @WebParam(name = "details", targetNamespace = "http://tempuri.org/")
        String details)
        throws IContentVaultServiceUpdateDataContentNotFoundFaultFaultFaultMessage
    ;

    /**
     * 
     * @param id
     * @param portrait
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "UpdatePortrait", action = "http://tempuri.org/IContentVaultService/UpdatePortrait")
    @WebResult(name = "UpdatePortraitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdatePortrait", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.UpdatePortrait")
    @ResponseWrapper(localName = "UpdatePortraitResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.UpdatePortraitResponse")
    public byte[] updatePortrait(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        ContentIdentifier id,
        @WebParam(name = "portrait", targetNamespace = "http://tempuri.org/")
        ContentBlob portrait);

    /**
     * 
     * @param id
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "RestoreBackup", action = "http://tempuri.org/IContentVaultService/RestoreBackup")
    @WebResult(name = "RestoreBackupResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RestoreBackup", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.RestoreBackup")
    @ResponseWrapper(localName = "RestoreBackupResponse", targetNamespace = "http://tempuri.org/", className = "nz.co.aetheric.magus.ioun.RestoreBackupResponse")
    public byte[] restoreBackup(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        ContentIdentifier id);

}
